CREATE TABLE public."Users" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" varchar NOT NULL,
	"Email" varchar NOT NULL,
	"Password" varchar NOT NULL,
	"UserAddress" jsonb NULL,
	"IsAdmin" bool NOT NULL,
	CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "IX_Users_IsAdmin" ON public."Users" USING btree ("IsAdmin");
